addons:
  postgresql: "9.6"
before_script:
  - DATA_DIR=./data scripts/create_cluster &
  - sleep 10 # wait a while -- create_cluster takes a few seconds to run
  - createdb -p 5433 rocket-rides-reads-test
  - psql -p 5433 rocket-rides-reads-test < schema.sql
env:
  global:
    - NUM_REPLICAS=5
    - POSTGRES_PORT=5433
language: ruby
notifications:
  email:
    on_success: never
rvm:
  - 2.4.0
sudo: false
